---
title: "Prediction Assignement"
output: html_notebook
author: "Michael Garcia"
date: "August 26, 2018"
---

## Purpose
The purpose of this analysis is to develop a model that will predict the
manner in which participants exercise. The study consists of 6 participants.
Accelerometers on the belt, forearm, arm, and dumbell will provide the data.


### Data Preparation

Source: http://web.archive.org/web/20161224072740/http:/groupware.les.inf.puc-rio.br/har

```{r fetchdata, echo=FALSE, include=TRUE}
url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/"
trainfile <- "pml-training.csv"
download.file(paste0(url,trainfile)
              ,destfile = paste0(getwd(),"/",trainfile))
testfile <- "pml-testing.csv"
download.file(paste0(url,testfile)
              ,destfile = paste0(getwd(),"/",testfile))
traindf <- read.csv(paste0(url,trainfile))
testdf <- read.csv(paste0(url,testfile))

unique(traindf$user_name)

```


### Data Management
Due to the size, a SQLite db engine will be used to query the data
```{r sqlite, echo=TRUE,include=TRUE}
library(DBI)
# Create an ephemeral in-memory RSQLite database
con <- dbConnect(RSQLite::SQLite(), ":memory:")


dbWriteTable(con, "traindata", traindf)
dbWriteTable(con, "testdata", testdf)
trainres <- dbSendQuery(con, "SELECT * FROM traindata")
###trainres <- dbGetQuery(con,"select * from traindata")
dbFetch(res = trainres,n=10)



###dbClearResult(res)
##dbDisconnect(con) 
```


### Pre-processing

```{r preprocess,  echo = TRUE, include= TRUE}
library(caret);library(kernlab);
inTrain <- createDataPartition(y=traindf$total_accel_arm
                               ,p=0.50, list = FALSE)
inTest <- createDataPartition(y=testdf$total_accel_arm
                               ,p=0.75, list = FALSE)
training <- traindf[inTrain,]
testing <- testdf[inTest,]

plot(training$total_accel_arm,training$)


```


